### ISSUE TITLE
Request: Open Quake Window in display where mouse pointer is.

### ISSUE THREAD

**Issue by erenfro** [repsac-by/gnome-shell-extension-quake-mode#65] opened 2022-11-04 02:36 UTC
Tilix and most quake/visor capable terminals support this feature to follow the mouse when opening the terminal, in the display where the mouse pointer is currently at.
I would love for this extension to be able to do the same, so in multi-monitor situations is becomes quite the useful little tool that I'm familiar with, but allowing me more control over which terminal application to use. Tilix is what I use now because it's the most reliable in my experience because the same command to open the terminal also can start it and toggle it's visibility.

**Comment by petre2dor** [comment] 2023-08-01 14:18
I think this issue is a duplicate of #32.
@erenfro please close it to lower the amount of work for the maintainers.

**Closed** 2023-08-02 04:58 UTC
Labels: enhancement
